Fee, Garage, and Ticket Class Implementation
aadiego/cs401-group4 pull request #6
Opened 2024-11-28 07:19 UTC by MajiPearson

Created the Fee, Garage, and Ticket class. Please review if it's good and if not let me know. I did not add the payment method to ticket yet because it has not been implemented so I commented it out but will add once we create the payment class.

2024-11-28 09:07 UTC, aadiego requested changes

2024-11-28 09:07 UTC, aadiego commented on src/main/java/ParkingGarage/Fee.java
> +			JSONObject feeJson = dataLoader.getJSONObject("Fee_" + id);
I think we should keep the top level clean, so all of the `Fee` objects will exist below the `Fee` parent.

For example:
`{
  "fee" : {
    "1": { ... },
    "2": { ... }.
    ...
  }
}`
vs
`{
  "fee_1" : { ... },
  "fee_2": { ... }.
  ...
}`

```suggestion
			JSONObject feeJson = dataLoader.getJSONObject("fee").getJSONObject(id);
```

2024-11-28 09:07 UTC, aadiego commented on src/main/java/ParkingGarage/Fee.java
> +		if (cost < 0) {
We're going to need something to generate the `id` in here as well. Maybe I can create a class that generates unique IDs that can be called?

2024-11-29 21:41 UTC, MajiPearson commented on src/main/java/ParkingGarage/Fee.java
> +		if (cost < 0) {
Yes I agree that we should create a separate class that is able to generate unique IDs and we can apply that class to all the other classes such as garage, fee, and ticket.

2024-11-29 23:02 UTC, aadiego approved these changes

2024-11-29 23:02 UTC, merged